chore: add maintainers as codeowners to all files
hashgraph/hedera-the-graph pull request #167
Opened 2024-12-13 09:17 UTC by PavelSBorisov

**Description**:
Update CODEOWNERS to provide maintainers ownership of all files in their repos

**Related issue(s)**:

Fixes #10 

**Notes for reviewer**:
N/A

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2024-12-13 13:58 UTC, andrewb1269hg requested changes

2024-12-13 13:58 UTC, andrewb1269hg commented on .github/CODEOWNERS
> +/auth-layer-proxy/                              @AlfredoG87 @Nana-EC @hashgraph/hedera-smart-contracts @hashgraph/release-engineering @hashgraph/release-engineering-managers
Alfredo is in the hedera-smart-contracts team and should be removed as an individual user.

2024-12-13 13:58 UTC, andrewb1269hg commented on .github/CODEOWNERS
> +/charts/auth-layer-proxy/                       @AlfredoG87 @Nana-EC @beeradb @hashgraph/hedera-smart-contracts @hashgraph/release-engineering @hashgraph/release-engineering-managers
Alfredo is in the hedera-smart-contracts team and should be removed as an individual user.

2024-12-13 13:58 UTC, andrewb1269hg commented on .github/CODEOWNERS
> +/charts/                                        @AlfredoG87 @Nana-EC @beeradb @hashgraph/hedera-smart-contracts @hashgraph/release-engineering @hashgraph/release-engineering-managers
Alfredo is in the hedera-smart-contracts team and should be removed as an individual user.

2024-12-13 13:58 UTC, andrewb1269hg commented on .github/CODEOWNERS
> +/subgraphs/                                     @AlfredoG87 @Nana-EC @hashgraph/hedera-smart-contracts @hashgraph/release-engineering @hashgraph/release-engineering-managers
Alfredo is in the hedera-smart-contracts team and should be removed as an individual user.

2024-12-13 14:51 UTC, andrewb1269hg approved these changes

2024-12-13 16:59 UTC, rbarkerSL requested changes

2024-12-13 16:59 UTC, rbarkerSL commented on .github/CODEOWNERS
>  /.github/                                       @hashgraph/devops-ci @hashgraph/devops-ci-committers @hashgraph/release-engineering @hashgraph/release-engineering-managers
```suggestion
/.github/                                       @hashgraph/devops-ci @hashgraph/devops-ci-committers @hashgraph/release-engineering @hashgraph/release-engineering-managers
/.github/workflows/                             @hashgraph/devops-ci @hashgraph/devops-ci-committers @hashgraph/release-engineering @hashgraph/release-engineering-managers @hashgraph/hedera-smart-contracts 
```

2024-12-16 13:45 UTC, andrewb1269hg approved these changes

2024-12-17 04:31 UTC, rbarkerSL approved these changes

2024-12-17 04:32 UTC, rbarkerSL approved these changes

2024-12-17 08:13 UTC, merged